FROM archlinux:base

RUN pacman -Sy --noconfirm archlinux-keyring
RUN pacman -Syyu --noconfirm
RUN pacman -S --noconfirm gnutls util-linux bash-completion cmake python git libfaketime
RUN pacman -S --noconfirm make gcc

# Setup language environment
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8

CMD ["/bin/bash"]
